"""initial migration

Revision ID: ab632e0707dd
Revises: 
Create Date: 2023-07-05 01:37:01.407709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab632e0707dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('label', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reminder', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('reminder')
        batch_op.drop_column('label')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
